"""Agregar campo verificado y token_verificacion

Revision ID: fd7dc1bd6e01
Revises: 
Create Date: 2025-05-01 20:17:15.695934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7dc1bd6e01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('token_verificacion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('token_verificacion')
        batch_op.drop_column('verificado')

    # ### end Alembic commands ###
